```{r, child="_styles.Rmd"}
```

## **Workshop modules**
Please use the links below to access materials (code, video, feeds) from R workshops. For new users, it is best to start with the introduction to R programming and then move on to more advanced topics.

<!-- <h3 id = "multi"><b>Available workshop content</b></h3> -->
<a href="./intro-home.html"><b>Introduction to R and RStudio</b></a>: an introductory stroll through key concepts and syntax in R. This session will cover the basics needed in others listed below.</br>

Here is a link to the [code we wrote during the live session Feb 12 2021](https://github.com/danStich/we-r-nycafs/blob/main/workshop_files/introductory_live.R).

<a href="./fishStats.html"><b>Introduction to fisheries statistics in R</b></a>: an introduction to methods and tools available for common fisheries analyses in R, including length-frequency histograms, proportional size distribution (PSD), growth curves, and length-weight regression. Methods are demonstrated using base R functionality in addition to functions available through the `FSA` package for R (<a href="https://github.com/droglenc/FSA">Ogle et al. 2020</a>). 

Here is a link to the [code we wrote during the live session Feb 19 2021](https://github.com/danStich/we-r-nycafs/blob/main/workshop_files/fishStats_live.R).


<a href="./intro_gis.html"><b>Introduction to spatial data for fisheries in R</b></a>: a (really basic) introduction to working with and plotting data commonly used in geographic information systems (GIS).

## **Workshop data**
All data and code for these workshops are available in a compressed (.zip) folder [here](https://github.com/danStich/we-r-nycafs/blob/main/workshop_files.zip). Just click download and save it wherever you like - be sure to unzip it if required on your operating system.

<h2 id = "multi"> **References** </h2>
Ogle, D.H., P. Wheeler, and A. Dinno. 2020. FSA: Fisheries Stock Analysis. R package version 0.8.30. Website:  [https://derekogle.com/fishR](https://derekogle.com/fishR)

<br> 
 